function analyzeLink(){

let loadingText = document.getElementById("loadingText");
let text = document.getElementById("inputBox").value.toLowerCase();
let result = document.getElementById("result");
let riskBar = document.getElementById("riskBar");
let tips = document.getElementById("tips");
let historyList = document.getElementById("historyList");
let feedList = document.getElementById("feedList");
let attackType = document.getElementById("attackType");

loadingText.innerHTML = "🤖 AI Scanning...";

setTimeout(() => {

let risk = 0;
let reasons = [];

if(text.includes("http")){
risk += 20;
reasons.push("Contains URL link");
}

if(text.includes("login")){
risk += 25;
reasons.push("Contains login keyword");
}

if(text.includes("security")){
risk += 20;
reasons.push("Contains security keyword");
}

if(text.includes("@")){
risk += 30;
reasons.push("Contains @ symbol");
}

if(text.includes("-")){
risk += 10;
reasons.push("Contains suspicious hyphen");
}

if(
text.includes("paypal") ||
text.includes("amazon") ||
text.includes("bank") ||
text.includes("netflix")
){
risk += 25;
reasons.push("Fake brand detected");
}

if(text.length > 40){
risk += 20;
reasons.push("Long suspicious link");
}

if(risk >= 60){

if(
text.includes("login") ||
text.includes("password") ||
text.includes("verify")
){
attackType.innerHTML = "🚨 Attack Type: Credential Phishing";
}
else if(
text.includes("paypal") ||
text.includes("amazon") ||
text.includes("netflix") ||
text.includes("bank")
){
attackType.innerHTML = "⚠️ Attack Type: Brand Impersonation";
}
else{
attackType.innerHTML = "⚠️ Attack Type: Suspicious Link";
}

document.getElementById("alarmSound").play();

tips.innerHTML =
"🚨 Security Tips:<br>" +
"- Do not enter passwords<br>" +
"- Avoid clicking suspicious links<br>" +
"- Verify the official website";

result.innerHTML =
"🚨 Phishing Detected<br>" +
"Risk Level: " + risk + "%<br><br>" +
"Threat Report:<br>" +
reasons.join("<br>");

result.style.color = "red";
}

else if(risk >= 30){

attackType.innerHTML = "⚠️ Attack Type: Suspicious Activity";

tips.innerHTML =
"⚠️ Be Careful:<br>" +
"- Double check the link<br>" +
"- Do not share personal data";

result.innerHTML =
"⚠️ Suspicious<br>" +
"Risk Level: " + risk + "%<br><br>" +
"Threat Report:<br>" +
reasons.join("<br>");

result.style.color = "orange";
}

else{

attackType.innerHTML = "✅ No Known Threat Detected";

tips.innerHTML =
"✅ Link appears safe<br>" +
"- Still verify trusted websites";

result.innerHTML =
"✅ Safe<br>" +
"Risk Level: " + risk + "%";

result.style.color = "lightgreen";
}

riskBar.style.width = risk + "%";

if(risk >= 60){
riskBar.style.background = "red";
}
else if(risk >= 30){
riskBar.style.background = "orange";
}
else{
riskBar.style.background = "lightgreen";
}

let newItem = document.createElement("li");
newItem.innerHTML = "🔍 " + text + "<br>Risk: " + risk + "%";
historyList.prepend(newItem);

let level = "";

if(risk >= 90){
level = "[CRITICAL]";
}
else if(risk >= 60){
level = "[HIGH]";
}
else if(risk >= 30){
level = "[MEDIUM]";
}
else{
level = "[LOW]";
}

let feedItem = document.createElement("li");
feedItem.innerHTML =
level + " " + attackType.innerText + " | Risk: " + risk + "%";

if(level === "[CRITICAL]"){
feedItem.style.borderLeft = "5px solid red";
}
else if(level === "[HIGH]"){
feedItem.style.borderLeft = "5px solid orange";
}
else if(level === "[MEDIUM]"){
feedItem.style.borderLeft = "5px solid yellow";
}
else{
feedItem.style.borderLeft = "5px solid lightgreen";
}

feedList.prepend(feedItem);

loadingText.innerHTML = "✅ Scan Complete";

}, 2000);

}

function downloadReport(){

let text = document.getElementById("inputBox").value;
let result = document.getElementById("result").innerText;
let tips = document.getElementById("tips").innerText;
let attackType = document.getElementById("attackType").innerText;

let report =
"=== PhishGuard Security Report ===\n\n" +
"Scanned Link / Message:\n" +
text + "\n\n" +
"Attack Type:\n" +
attackType + "\n\n" +
"Analysis Result:\n" +
result + "\n\n" +
"Security Tips:\n" +
tips + "\n\n" +
"Generated by PhishGuard AI";

let blob = new Blob([report], { type: "text/plain" });
let link = document.createElement("a");

link.href = URL.createObjectURL(blob);
link.download = "PhishGuard_Report.txt";
link.click();

}